// Package po generated by 'freedom new-po'
package po

import (
	"gorm.io/gorm"
	"time"
)

// Account .
type Account struct {
	changes  map[string]interface{}
	Created  time.Time `gorm:"column:created"`
	Updated  time.Time `gorm:"column:updated"`
	UID      int       `gorm:"primaryKey;column:uid"`
	Age      int       `gorm:"column:age"`
	Status   int8      `gorm:"column:status"`
	Name     string    `gorm:"column:name"`
	Password string    `gorm:"column:password"`
}

// TableName .
func (obj *Account) TableName() string {
	return "account"
}

// Location .
func (obj *Account) Location() map[string]interface{} {
	return map[string]interface{}{"uid": obj.UID}
}

// GetChanges .
func (obj *Account) GetChanges() map[string]interface{} {
	if obj.changes == nil {
		return nil
	}
	result := make(map[string]interface{})
	for k, v := range obj.changes {
		result[k] = v
	}
	obj.changes = nil
	return result
}

// Update .
func (obj *Account) Update(name string, value interface{}) {
	if obj.changes == nil {
		obj.changes = make(map[string]interface{})
	}
	obj.changes[name] = value
}

// SetCreated .
func (obj *Account) SetCreated(created time.Time) {
	obj.Created = created
	obj.Update("created", created)
}

// SetUpdated .
func (obj *Account) SetUpdated(updated time.Time) {
	obj.Updated = updated
	obj.Update("updated", updated)
}

// SetAge .
func (obj *Account) SetAge(age int) {
	obj.Age = age
	obj.Update("age", age)
}

// SetStatus .
func (obj *Account) SetStatus(status int8) {
	obj.Status = status
	obj.Update("status", status)
}

// SetName .
func (obj *Account) SetName(name string) {
	obj.Name = name
	obj.Update("name", name)
}

// SetPassword .
func (obj *Account) SetPassword(password string) {
	obj.Password = password
	obj.Update("password", password)
}

// AddAge .
func (obj *Account) AddAge(age int) {
	obj.Age += age
	obj.Update("age", gorm.Expr("age + ?", age))
}
