// Package po generated by 'freedom new-po'
package po

import (
	"gorm.io/gorm"
	"time"
)

// User .
type User struct {
	changes map[string]interface{}
	Created time.Time `gorm:"column:created"`
	Updated time.Time `gorm:"column:updated"`
	UserID  int       `gorm:"primaryKey;column:userId"`
	Age     int       `gorm:"column:age"`
	Sex     int8      `gorm:"column:sex"`
	Name    string    `gorm:"column:name"`
	Address string    `gorm:"column:address"`
}

// TableName .
func (obj *User) TableName() string {
	return "user"
}

// Location .
func (obj *User) Location() map[string]interface{} {
	return map[string]interface{}{"userId": obj.UserID}
}

// GetChanges .
func (obj *User) GetChanges() map[string]interface{} {
	if obj.changes == nil {
		return nil
	}
	result := make(map[string]interface{})
	for k, v := range obj.changes {
		result[k] = v
	}
	obj.changes = nil
	return result
}

// Update .
func (obj *User) Update(name string, value interface{}) {
	if obj.changes == nil {
		obj.changes = make(map[string]interface{})
	}
	obj.changes[name] = value
}

// SetCreated .
func (obj *User) SetCreated(created time.Time) {
	obj.Created = created
	obj.Update("created", created)
}

// SetUpdated .
func (obj *User) SetUpdated(updated time.Time) {
	obj.Updated = updated
	obj.Update("updated", updated)
}

// SetAge .
func (obj *User) SetAge(age int) {
	obj.Age = age
	obj.Update("age", age)
}

// SetSex .
func (obj *User) SetSex(sex int8) {
	obj.Sex = sex
	obj.Update("sex", sex)
}

// SetName .
func (obj *User) SetName(name string) {
	obj.Name = name
	obj.Update("name", name)
}

// SetAddress .
func (obj *User) SetAddress(address string) {
	obj.Address = address
	obj.Update("address", address)
}

// AddAge .
func (obj *User) AddAge(age int) {
	obj.Age += age
	obj.Update("age", gorm.Expr("age + ?", age))
}
