services:
  postgres:
    image: postgres:14.6
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 111111
      POSTGRES_DB: x-project
    volumes:
      - ./tmp/postgres:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  redis:
    image: redis:latest
    volumes:
      - ./tmp/redis:/data
    ports:
      - "6380:6379"

  minio:
    image: minio/minio:latest
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - ./tmp/minio:/data
    ports:
      - "9000:9000"
      - "9001:9001"

  app:
    build: .
    depends_on:
      - postgres
      - redis
      - minio
    ports:
      - "18000:18000"
    volumes:
      - ./config:/etc/x-project