//Package domain generated by 'freedom new-project x-freedom'
package domain

import (
	"github.com/8treenet/freedom"
	"x-freedom/adapter/repository"
)

func init() {
	freedom.Prepare(func(initiator freedom.Initiator) {
		initiator.BindService(func() *Default {
			return &Default{}
		})
		initiator.InjectController(func(ctx freedom.Context) (service *Default) {
			initiator.FetchService(ctx, &service)
			return
		})
	})
}

// Default .
type Default struct {
	Worker  freedom.Worker
	DefRepo *repository.Default
}

// RemoteInfo .
func (s *Default) RemoteInfo() (result struct {
	Ip string
	Ua string
}) {
	s.Worker.Logger().Info("I'm service")
	result.Ip = s.DefRepo.GetIP()
	result.Ua = s.DefRepo.GetUA()
	return
}
